apiVersion: apps/v1
kind: Deployment
metadata:
  name: message
  labels:
    app: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - name: message
          image: 247785678011.dkr.ecr.us-east-2.amazonaws.com/message:1.0
          ports:
            - containerPort: 8080