apiVersion: apps/v1
kind: Deployment
metadata:
  name: room
  labels:
    app: room
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room
  template:
    metadata:
      labels:
        app: room
    spec:
      containers:
        - name: room
          image: 247785678011.dkr.ecr.us-east-2.amazonaws.com/room:1.0
          ports:
            - containerPort: 8080